-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Create blogs table
create table public.blogs (
  id bigint generated by default as identity primary key,
  name text not null,
  url text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null
);

-- Create posts table
create table public.posts (
  id bigint generated by default as identity primary key,
  blog_name text not null,
  title text not null,
  date date not null,
  content text not null,
  link text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  blog_id bigint references public.blogs(id) on delete cascade
);

-- Enable RLS
alter table public.blogs enable row level security;
alter table public.posts enable row level security;

-- Policies for blogs
-- Anyone can view blogs
create policy "Public blogs are viewable by everyone"
  on public.blogs for select
  using ( true );

-- Authenticated users can insert their own blogs
create policy "Users can insert their own blogs"
  on public.blogs for insert
  with check ( auth.uid() = user_id );

-- Authenticated users can update their own blogs
create policy "Users can update own blogs"
  on public.blogs for update
  using ( auth.uid() = user_id );

-- Authenticated users can delete their own blogs
create policy "Users can delete own blogs"
  on public.blogs for delete
  using ( auth.uid() = user_id );

-- Policies for posts
-- Anyone can view posts
create policy "Public posts are viewable by everyone"
  on public.posts for select
  using ( true );

-- Authenticated users can insert posts (linked to their blogs implicitly or just allow auth users)
-- Since posts are usually crawled, maybe we allow any authenticated user to add posts? 
-- Or strictly enforce ownership via blog_id? 
-- For simplicity in this demo, let's allow authenticated users to manage posts.
create policy "Authenticated users can insert posts"
  on public.posts for insert
  with check ( auth.role() = 'authenticated' );

create policy "Authenticated users can update posts"
  on public.posts for update
  using ( auth.role() = 'authenticated' );

create policy "Authenticated users can delete posts"
  on public.posts for delete
  using ( auth.role() = 'authenticated' );

-- Set up Realtime
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table public.blogs;
alter publication supabase_realtime add table public.posts;
